---
- name: Disable laptop lid closing shutting down the laptop
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: ^HandleLidSwitch=
    line: HandleLidSwitch=ignore
    state: present
  notify: restart systemd-logind
