---
# VXLAN Zone (Cluster-wide network)
# Name
sdn_vxlan_id: arc2
# Comma-separated (Zerotier) IPs for all nodes
sdn_vxlan_peer_ips: "{{ lookup('env', 'VXLAN_PEER_IPS') }}"

# VNets
# (ID needs to be <=8 characters)
sdn_vnets:
  - id: PApp
    alias: ProdApp
    cidr: fd5e:934f:acab:0001::/64
    tag: 101
