---
- name: Disable enterprise Proxmox repository
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Disable enterprise Ceph repository
  file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: Enable community repository
  lineinfile:
    path: /etc/apt/sources.list.d/pve-community.list
    line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    create: true
    state: present

- name: Update APT package index & upgrade
  apt:
    update_cache: true
    upgrade: full

- name: Add SSH key (gk)
  ansible.posix.authorized_key:
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINpmdkxAZH3See4FaPgiZoTxpcEC1orOGB9cXoQtYUYI a1
    user: root

- name: Add SSH key (current)
  ansible.posix.authorized_key:
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
    user: root
  ignore_errors: true

- name: Disallow SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: sshd -t -f %s
  notify:
    - restart sshd