---
- name: Disable enterprise Proxmox repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Disable enterprise Ceph repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: Enable community repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-community.list
    line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    create: true
    state: present

- name: Update APT package index & upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoclean: true
    autoremove: true
    clean: true

- name: Add SSH key (gk)
  ansible.posix.authorized_key:
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINpmdkxAZH3See4FaPgiZoTxpcEC1orOGB9cXoQtYUYI a1
    user: root

- name: Add SSH key (current)
  ansible.posix.authorized_key:
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
    user: root
  ignore_errors: true

- name: Disallow SSH password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: sshd -t -f %s
  notify:
    - restart sshd

- name: Install SSHGuard
  ansible.builtin.apt:
    package: sshguard

- name: Install dnsmasq
  ansible.builtin.apt:
    package: dnsmasq

- name: Add automatic upgrades to cron
  ansible.builtin.cron:
    name: upgrade
    user: root
    minute: 15
    hour: 12
    weekday: "2" # Wednesday
    job: /usr/bin/apt-get update && /usr/bin/apt-get -y dist-upgrade
