---
- name: Create /etc/pve/firewall/
  ansible.builtin.file:
    path: /etc/pve/firewall/
    state: directory
    group: www-data

- name: Configure cluster firewall
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/pve/firewall/
    group: www-data
    unsafe_writes: true
  ignore_errors: true
  with_fileglob:
    - ../rules/*
