name: "Push to Cachix"
on:
  push:
  pull_request:

jobs:
  cachix:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [x86_64-linux]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v14
        if: github.ref == 'refs/heads/main'
        with:
          name: gk-arc2
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      # Build & push the Nix cache
      - name: Push to cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix-store -qR --include-outputs \
          $(nix-store -q --deriver \
          $(nix build .#checks.${{ matrix.system }}.deploy-activate --print-out-paths --no-link)) \
          | cachix push gk-arc2
